### PR TITLE
DCC 5304 Portal UI - Mutation ID on the OncoGrid Crosshair

### PR DESCRIPTION
**Pull request by SidSyrus**
Adding mutation ID to crosshair tooltip overlay

### CODE REVIEW

**Comment by Jephuff** [comment]
I think it probably makes sense to make this change higher up (where the OncoGrid is being used) That template probably should just be a very generic  placeholder and for any additional information the user can override.

**Comment by SidSyrus** [comment]
You mean we should have this as one of the setting params so it can be customized?

**Comment by Jephuff** [comment]
Yep, it already is. 
`params.templates.mainGridCrosshair`
so you could do something like
```
new OncoGrid({
  templates: {
    mainGridCrosshair: '{{#donor}}Donor: {{donor.id}}<br>{{/donor}}' +
        '{{#gene}}Gene: {{gene.symbol}}<br>{{/gene}}' +
        '{{#observation}}Mutation: {{observation.id}}<br>{{/observation}}'
  },
  ...
});
```

**Comment by SidSyrus** [comment]
Ahh ok I see. Thanks.

**Pull request closed without merging**
